char *getblock(unsigned int atl, int iof);
char *getline(unsigned int tl);
int advance(char *lp, char *ep);
int append(int (*f)(void), unsigned int *a);
int cclass(char *set, int c, int af);
void commands(void);
void compile(int eof);
int execute(unsigned int *addr);
void filename(int comm);
int getchr(void);
int getfile(void);
void global(int k);
void init(void);
void print(void);
void putchr(int ac);
int putline(void);
int puts(char *sp);
void setwide(void);
void gvars(void);
void pattern_init(int arc, char* arv[]);
int file_init(int arc, char* arv[]);
int dir_list(char* dirv[]);
void reset(int uf);